/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e0e3e5",
        "outline": "#727785",
        "secondary": "#545f73",
        "tertiary": "#924700",
        "surface-tint": "#005ac2",
        "primary-fixed-dim": "#adc6ff",
        "primary": "#0058be",
        "on-surface-variant": "#424754",
        "outline-variant": "#c2c6d6",
        "inverse-surface": "#2d3133",
        "on-secondary-fixed": "#111c2d",
        "secondary-fixed-dim": "#bcc7de",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-container": "#586377",
        "on-error-container": "#93000a",
        "surface-container-high": "#e6e8ea",
        "on-surface": "#191c1e",
        "surface-bright": "#f7f9fb",
        "tertiary-fixed-dim": "#ffb786",
        "on-secondary-fixed-variant": "#3c475a",
        "on-background": "#191c1e",
        "on-tertiary": "#ffffff",
        "surface-container": "#eceef0",
        "secondary-fixed": "#d8e3fb",
        "error-container": "#ffdad6",
        "surface-container-low": "#f2f4f6",
        "background": "#f7f9fb",
        "surface": "#f7f9fb",
        "on-primary": "#ffffff",
        "primary-fixed": "#d8e2ff",
        "tertiary-fixed": "#ffdcc6",
        "on-tertiary-container": "#fffbff",
        "surface-dim": "#d8dadc",
        "error": "#ba1a1a",
        "surface-container-highest": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "tertiary-container": "#b75b00",
        "on-primary-container": "#fefcff",
        "on-primary-fixed-variant": "#004395",
        "on-tertiary-fixed": "#311400",
        "inverse-primary": "#adc6ff",
        "on-primary-fixed": "#001a42",
        "secondary-container": "#d5e0f8",
        "on-tertiary-fixed-variant": "#723600",
        "primary-container": "#2170e4"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "sidebar-width": "280px",
        md: "16px",
        xs: "4px",
        sm: "8px",
        gutter: "24px",
        base: "4px",
        "container-max-width": "1440px",
        lg: "24px",
        xl: "32px"
      },
      fontFamily: {
        "display-lg": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "label-sm": ["Geist"],
        "body-md": ["Inter"],
        "label-md": ["Geist"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
